"""Item factory for figural questions.

Hand-writing every matrix, analogy and series item does not scale, and doing it
by hand is also where ambiguity and wrong distractors creep in. This builds the
item from an explicit rule list instead, which means:

  * the key is computed, not typed, so it is always right;
  * every distractor is generated by omitting exactly one rule, which is how
    real CogAT / NNAT / OLSAT distractors are built;
  * the explanation is written from the same rule list, so it always names the
    right wrong answer and describes the right transformation.

Difficulty is the number of simultaneous rules, capped per grade from the
working-memory evidence in docs/research/difficulty-model.md: two rules at
grades 1-2, three at grades 3-4.

Rotation values follow Blum & Holling's measured difficulty ordering:
90 clockwise is easiest, then reflection, then 180, then 90 anticlockwise.
Grades 1-2 use 90 clockwise only.
"""
import random

# ---------------------------------------------------------------- rules

class Rule:
    """One transformation, plus the words to describe it to a child."""
    def __init__(self, key, value, phrase, undone):
        self.key = key          # shape attribute to set
        self.value = value      # value to set it to
        self.phrase = phrase    # "it fills in"
        self.undone = undone    # "never filled in"

    def apply(self, shape):
        out = dict(shape)
        if self.value is None:
            out.pop(self.key, None)
        else:
            out[self.key] = self.value
        return out


def fill_solid():   return Rule('f', None, 'the shape fills in', 'never filled in')
def fill_outline(): return Rule('f', 'outline', 'the shape empties out', 'stayed filled in')
def fill_to(f, word): return Rule('f', f, f'the inside becomes {word}', f'did not become {word}')
def recolor(c):     return Rule('c', c, f'the color turns {c}', f'kept the old color')
def rotate(deg):
    words = {90: 'turns a quarter turn', 180: 'turns upside down', 270: 'turns three quarters of the way round'}
    return Rule('r', deg, f'the shape {words[deg]}', 'did not turn')
def resize(z, bigger): return Rule('z', z, f'the shape gets {"bigger" if bigger else "smaller"}',
                                   f'did not get {"bigger" if bigger else "smaller"}')
def recount(n):     return Rule('n', n, f'there are {n} of them instead', 'kept the old number')


def apply_all(shape, rules):
    out = dict(shape)
    for r in rules:
        out = r.apply(out)
    return out


# ---------------------------------------------------------------- distractors

def build_choices(base, rules, invariant_breaker, n_choices, rng, colors=None):
    """
    The key applies every rule. One distractor per rule applies everything but
    that rule. One more changes something the item held still. Extra slots get a
    near miss on the key.
    """
    key = apply_all(base, rules)
    items = [('key', key, None)]

    for i, r in enumerate(rules):
        others = [x for j, x in enumerate(rules) if j != i]
        cand = apply_all(base, others)
        if cand != key:
            items.append(('omit', cand, r))

    if invariant_breaker:
        cand = invariant_breaker(dict(key))
        if cand != key:
            items.append(('invariant', cand, None))

    # Near misses: nudge one attribute of the key without touching a rule.
    near = []
    if any(r.key == 'r' for r in rules):
        deg = key.get('r', 0)
        for alt in (270, 180, 90):
            if alt != deg:
                near.append(dict(key, r=alt))
    if any(r.key == 'n' for r in rules):
        n = key.get('n', 1)
        for alt in (n + 1, n - 1, n + 2):
            if 1 <= alt <= 9 and alt != n:
                near.append(dict(key, n=alt))
    if any(r.key == 'z' for r in rules):
        z = key.get('z', 1)
        near.append(dict(key, z=round(min(1.5, max(0.3, z * (0.6 if z > 0.7 else 1.7))), 2)))
    rng.shuffle(near)
    for cand in near:
        if len(items) >= n_choices:
            break
        if all(cand != it[1] for it in items):
            items.append(('near', cand, None))

    # Last resort filler: a different colour. Must stay inside the caller's
    # palette, because the NNAT is restricted to five validated colours.
    fallback = list(colors) if colors else ['blue', 'green', 'yellow', 'red']
    while len(items) < n_choices:
        cand = dict(key, c=rng.choice(fallback))
        if all(cand != it[1] for it in items):
            items.append(('near', cand, None))
        else:
            cand = dict(key, z=round(rng.uniform(0.4, 1.3), 2))
            if all(cand != it[1] for it in items):
                items.append(('near', cand, None))
            else:
                break

    items = items[:n_choices]
    return items


def letter_ids(items):
    """Key first as 'a', matching the rest of the bank. The app shuffles."""
    ids = 'abcdef'
    out = []
    for i, (kind, shape, rule) in enumerate(items):
        out.append((ids[i], kind, shape, rule))
    return out


def explain(rules, tagged, subject='the shape'):
    """Write the explanation from the rules, naming a real wrong choice."""
    phrases = [r.phrase for r in rules]
    if len(phrases) == 1:
        head = f"Going across, {phrases[0]}."
    elif len(phrases) == 2:
        head = f"Two things change: {phrases[0]}, and {phrases[1]}."
    else:
        head = f"Three things change: {', '.join(phrases[:-1])}, and {phrases[-1]}."

    misses = [(cid, rule) for cid, kind, shape, rule in tagged if kind == 'omit' and rule]
    tail = ''
    if misses:
        cid, rule = misses[0]
        tail = f" Choice {cid} {rule.undone}."
        if len(misses) > 1:
            cid2, rule2 = misses[1]
            tail += f" Choice {cid2} {rule2.undone}."
    return head + tail


# ---------------------------------------------------------------- palettes

# Pearson validated exactly these five for the NNAT.
NNAT_COLORS = ['blue', 'green', 'yellow', 'grey']
FULL_COLORS = ['blue', 'green', 'yellow', 'red', 'purple', 'orange', 'teal', 'pink']

# Abstract geometry only, in rough order of how ordinary they look to a child.
SHAPES_SIMPLE = ['circle', 'square', 'triangle', 'diamond', 'star', 'heart', 'hexagon', 'pentagon']
SHAPES_WIDE = SHAPES_SIMPLE + [
    'octagon', 'star6', 'star4', 'trapezoid', 'parallelogram', 'kite', 'chevron',
    'bowtie', 'cross', 'plus', 'ring', 'semicircle', 'crescent', 'righttriangle',
    'arrow', 'oval', 'triangledown', 'moon', 'rectwide', 'recttall', 'lightning',
    'cloud', 'leaf', 'flag', 'house',
]
# The NNAT uses no recognisable objects.
SHAPES_ABSTRACT = [s for s in SHAPES_WIDE if s not in
                   ('leaf', 'flag', 'house', 'cloud', 'lightning', 'heart', 'moon', 'crescent')]

FILL_WORDS = {'stripesd': 'stripes', 'stripesh': 'flat stripes', 'stripesv': 'upright stripes',
              'dots': 'dots', 'grid': 'a criss cross pattern'}


def rot_choices(grade):
    """Rotation angles a child at this grade can actually verify."""
    if grade <= 1:
        return [90]
    if grade == 2:
        return [90, 180]
    if grade == 3:
        return [90, 180]
    return [90, 180, 270]


def rule_pool(grade, rng, colors):
    """Rules available at a grade, as zero-argument factories."""
    pool = [
        lambda: fill_solid(),
        lambda: fill_outline(),
        lambda: recolor(rng.choice(colors)),
        lambda: resize(1.2, True),
        lambda: resize(0.5, False),
        lambda: rotate(rng.choice(rot_choices(grade))),
    ]
    if grade >= 2:
        pool.append(lambda: recount(rng.choice([2, 3, 4])))
        f = rng.choice(list(FILL_WORDS))
        pool.append(lambda: fill_to(f, FILL_WORDS[f]))
    return pool


def pick_rules(grade, count, base, rng, colors):
    """Choose `count` rules that all actually change `base` and do not collide."""
    pool = rule_pool(grade, rng, colors)
    rng.shuffle(pool)
    chosen, used_keys = [], set()
    for make in pool:
        if len(chosen) == count:
            break
        r = make()
        if r.key in used_keys:
            continue
        if r.apply(base) == base:
            continue
        chosen.append(r)
        used_keys.add(r.key)
    return chosen


def max_rules(grade):
    """Working-memory ceiling. See docs/research/difficulty-model.md."""
    return 2 if grade <= 2 else 3


# ---------------------------------------------------------------- description

SHAPE_WORDS = {
    'star6': 'six-pointed star', 'star4': 'four-pointed star',
    'righttriangle': 'right triangle', 'triangledown': 'upside-down triangle',
    'rectwide': 'wide rectangle', 'recttall': 'tall rectangle',
    'semicircle': 'half circle', 'parallelogram': 'slanted rectangle',
    'lightning': 'lightning bolt', 'bowtie': 'bow tie', 'plus': 'plus sign',
    'ring': 'ring', 'dot': 'dot', 'line': 'bar', 'oval': 'oval',
}
PLURALS = {'cross': 'crosses', 'bow tie': 'bow ties', 'box': 'boxes',
           'leaf': 'leaves', 'half circle': 'half circles', 'diamond': 'diamonds'}
COUNT_WORDS = {2: 'two', 3: 'three', 4: 'four', 5: 'five', 6: 'six',
               7: 'seven', 8: 'eight', 9: 'nine'}


def shape_word(name, plural=False):
    word = SHAPE_WORDS.get(name, name)
    if not plural:
        return word
    if word in PLURALS:
        return PLURALS[word]
    if word.endswith(('s', 'x', 'ch', 'sh')):
        return word + 'es'
    return word + 's'


def article(word):
    return 'an' if word[0].lower() in 'aeiou' else 'a'


def describe(shape, capital=False):
    """Plain words for one shape. This is what the read-aloud voice speaks."""
    n = shape.get('n', 1)
    adjectives = []

    z = shape.get('z', 1)
    if z <= 0.65:
        adjectives.append('small')
    elif z >= 1.15:
        adjectives.append('big')

    f = shape.get('f')
    if f == 'outline':
        adjectives.append('empty')
    adjectives.append(shape.get('c', 'blue'))

    noun = shape_word(shape['s'], plural=n > 1)
    phrase = ' '.join(adjectives + [noun])

    if n > 1:
        phrase = f"{COUNT_WORDS.get(n, n)} {phrase}"
    else:
        phrase = f"{article(phrase)} {phrase}"

    extras = []
    if f in FILL_WORDS:
        extras.append(f"with {FILL_WORDS[f]} inside")
    r = shape.get('r')
    if r:
        extras.append({90: 'turned a quarter turn', 180: 'turned upside down',
                       270: 'turned three quarters of the way round'}[r])
    if extras:
        phrase = phrase + ', ' + ' and '.join(extras)

    return phrase[0].upper() + phrase[1:] if capital else phrase
